# In this assignment, you will create a Python program that generates an HTML page based on user input. The program will prompt the user to enter their name and a list of hobbies, separated by commas as a single input string. It will then parse the input and use it to construct an HTML page.

# The HTML page generated by your program should include the following elements:

# A <title> element containing the user's name.
# An <h1> element containing the user's name as the main heading.
# An <h2> element indicating the section for hobbies.
# A <p> element providing any additional information or instructions.
# An unordered list (`<ul>`) displaying the list of hobbies entered by the user.
# Your program should ensure proper HTML structure by including essential elements such as <html>, <head>, <title>, and <body>. Additionally, it should handle potential errors or unexpected input gracefully.

# You will be graded based on the clarity and effectiveness of your input prompt, the accuracy of input parsing, the correctness of HTML structure and content generation, as well as the overall functionality and readability of your code.

# To earn bonus points, you can add extra styling or customization to the HTML page, such as using CSS for formatting or incorporating additional visual elements.

# By completing this assignment, you will not only practice working with user input and file I/O in Python but also gain experience in generating HTML content dynamically from within a Python program.

